move root check to top

diff --git a/oaiharvester b/oaiharvester
--- a/oaiharvester
+++ b/oaiharvester
@@ -14,6 +14,9 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
+# root check
+[ $(whoami) == "root" ] && echo "Don't use this tool logged in as root." && exit 1
+
 VERSION="2.0.0_pre"
 VERB="ListRecords"
 CONFIGFILE="/etc/shell-oaiharvester/config.xml"
@@ -70,14 +73,6 @@ function die {
 
 trap cleanup SIGHUP SIGINT SIGTERM
 
-# root check
-[ $(whoami) == "root" ] && die "Don't use this tool logged in as root."
-
-# dependency check
-for dep in bc curl grep xsltproc; do
-	which ${dep} &>/dev/null || die "Dependency not found: ${dep}"
-done
-
 # Reading options
 if ! args=$(getopt -n "$0" -o "c:dhlmnr:tvz" \
 	-l "compress,config:,dev,help,list-repos,migrate,no-records,repository:,test,version" -- "$@")
@@ -101,6 +96,11 @@ while true ; do
 		*) die "$0: Internal error!" ;;
 	esac
 	shift
+done
+
+# dependency check
+for dep in bc curl grep xsltproc; do
+	which ${dep} &>/dev/null || die "Dependency not found: ${dep}"
 done
 
 # Loading functions
